/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: release-1.16
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.coding.apiserver.models;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;

/**
 * SupplementalGroupsStrategyOptions defines the strategy type and options used to create the strategy. Deprecated: use SupplementalGroupsStrategyOptions from policy API Group instead.
 */
@ApiModel(description = "SupplementalGroupsStrategyOptions defines the strategy type and options used to create the strategy. Deprecated: use SupplementalGroupsStrategyOptions from policy API Group instead.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-04-29T07:27:12.312Z[Etc/UTC]")
public class ExtensionsVSupplementalGroupsStrategyOptions {
  public static final String SERIALIZED_NAME_RANGES = "ranges";
  @SerializedName(SERIALIZED_NAME_RANGES)
  private List<ExtensionsVIDRange> ranges = null;

  public static final String SERIALIZED_NAME_RULE = "rule";
  @SerializedName(SERIALIZED_NAME_RULE)
  private String rule;


  public ExtensionsVSupplementalGroupsStrategyOptions ranges(List<ExtensionsVIDRange> ranges) {

    this.ranges = ranges;
    return this;
  }

  public ExtensionsVSupplementalGroupsStrategyOptions addRangesItem(ExtensionsVIDRange rangesItem) {
    if (this.ranges == null) {
      this.ranges = new ArrayList<ExtensionsVIDRange>();
    }
    this.ranges.add(rangesItem);
    return this;
  }

   /**
   * ranges are the allowed ranges of supplemental groups.  If you would like to force a single supplemental group then supply a single range with the same start and end. Required for MustRunAs.
   * @return ranges
  **/

  @ApiModelProperty(value = "ranges are the allowed ranges of supplemental groups.  If you would like to force a single supplemental group then supply a single range with the same start and end. Required for MustRunAs.")

  public List<ExtensionsVIDRange> getRanges() {
    return ranges;
  }


  public void setRanges(List<ExtensionsVIDRange> ranges) {
    this.ranges = ranges;
  }


  public ExtensionsVSupplementalGroupsStrategyOptions rule(String rule) {

    this.rule = rule;
    return this;
  }

   /**
   * rule is the strategy that will dictate what supplemental groups is used in the SecurityContext.
   * @return rule
  **/

  @ApiModelProperty(value = "rule is the strategy that will dictate what supplemental groups is used in the SecurityContext.")

  public String getRule() {
    return rule;
  }


  public void setRule(String rule) {
    this.rule = rule;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExtensionsVSupplementalGroupsStrategyOptions extensionsV1beta1SupplementalGroupsStrategyOptions = (ExtensionsVSupplementalGroupsStrategyOptions) o;
    return Objects.equals(this.ranges, extensionsV1beta1SupplementalGroupsStrategyOptions.ranges) &&
        Objects.equals(this.rule, extensionsV1beta1SupplementalGroupsStrategyOptions.rule);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ranges, rule);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExtensionsV1beta1SupplementalGroupsStrategyOptions {\n");
    sb.append("    ranges: ").append(toIndentedString(ranges)).append("\n");
    sb.append("    rule: ").append(toIndentedString(rule)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

