/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: release-1.16
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.coding.apiserver.models;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;

/**
 * IngressSpec describes the Ingress the user wishes to exist.
 */
@ApiModel(description = "IngressSpec describes the Ingress the user wishes to exist.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-04-29T07:27:12.312Z[Etc/UTC]")
public class NetworkingVIngressSpec {
  public static final String SERIALIZED_NAME_BACKEND = "backend";
  @SerializedName(SERIALIZED_NAME_BACKEND)
  private NetworkingVIngressBackend backend;

  public static final String SERIALIZED_NAME_RULES = "rules";
  @SerializedName(SERIALIZED_NAME_RULES)
  private List<NetworkingVIngressRule> rules = null;

  public static final String SERIALIZED_NAME_TLS = "tls";
  @SerializedName(SERIALIZED_NAME_TLS)
  private List<NetworkingVIngressTLS> tls = null;


  public NetworkingVIngressSpec backend(NetworkingVIngressBackend backend) {

    this.backend = backend;
    return this;
  }

   /**
   * Get backend
   * @return backend
  **/

  @ApiModelProperty(value = "")

  public NetworkingVIngressBackend getBackend() {
    return backend;
  }


  public void setBackend(NetworkingVIngressBackend backend) {
    this.backend = backend;
  }


  public NetworkingVIngressSpec rules(List<NetworkingVIngressRule> rules) {

    this.rules = rules;
    return this;
  }

  public NetworkingVIngressSpec addRulesItem(NetworkingVIngressRule rulesItem) {
    if (this.rules == null) {
      this.rules = new ArrayList<NetworkingVIngressRule>();
    }
    this.rules.add(rulesItem);
    return this;
  }

   /**
   * A list of host rules used to configure the Ingress. If unspecified, or no rule matches, all traffic is sent to the default backend.
   * @return rules
  **/

  @ApiModelProperty(value = "A list of host rules used to configure the Ingress. If unspecified, or no rule matches, all traffic is sent to the default backend.")

  public List<NetworkingVIngressRule> getRules() {
    return rules;
  }


  public void setRules(List<NetworkingVIngressRule> rules) {
    this.rules = rules;
  }


  public NetworkingVIngressSpec tls(List<NetworkingVIngressTLS> tls) {

    this.tls = tls;
    return this;
  }

  public NetworkingVIngressSpec addTlsItem(NetworkingVIngressTLS tlsItem) {
    if (this.tls == null) {
      this.tls = new ArrayList<NetworkingVIngressTLS>();
    }
    this.tls.add(tlsItem);
    return this;
  }

   /**
   * TLS configuration. Currently the Ingress only supports a single TLS port, 443. If multiple members of this list specify different hosts, they will be multiplexed on the same port according to the hostname specified through the SNI TLS extension, if the ingress controller fulfilling the ingress supports SNI.
   * @return tls
  **/

  @ApiModelProperty(value = "TLS configuration. Currently the Ingress only supports a single TLS port, 443. If multiple members of this list specify different hosts, they will be multiplexed on the same port according to the hostname specified through the SNI TLS extension, if the ingress controller fulfilling the ingress supports SNI.")

  public List<NetworkingVIngressTLS> getTls() {
    return tls;
  }


  public void setTls(List<NetworkingVIngressTLS> tls) {
    this.tls = tls;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NetworkingVIngressSpec networkingV1beta1IngressSpec = (NetworkingVIngressSpec) o;
    return Objects.equals(this.backend, networkingV1beta1IngressSpec.backend) &&
        Objects.equals(this.rules, networkingV1beta1IngressSpec.rules) &&
        Objects.equals(this.tls, networkingV1beta1IngressSpec.tls);
  }

  @Override
  public int hashCode() {
    return Objects.hash(backend, rules, tls);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NetworkingV1beta1IngressSpec {\n");
    sb.append("    backend: ").append(toIndentedString(backend)).append("\n");
    sb.append("    rules: ").append(toIndentedString(rules)).append("\n");
    sb.append("    tls: ").append(toIndentedString(tls)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

