/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: release-1.16
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.coding.apiserver.models;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * MetricIdentifier defines the name and optionally selector for a metric
 */
@ApiModel(description = "MetricIdentifier defines the name and optionally selector for a metric")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-04-29T07:27:12.312Z[Etc/UTC]")
public class VMetricIdentifier {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_SELECTOR = "selector";
  @SerializedName(SERIALIZED_NAME_SELECTOR)
  private VLabelSelector selector;


  public VMetricIdentifier name(String name) {

    this.name = name;
    return this;
  }

  /**
   * name is the name of the given metric
   * @return name
   **/
  @ApiModelProperty(required = true, value = "name is the name of the given metric")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public VMetricIdentifier selector(VLabelSelector selector) {

    this.selector = selector;
    return this;
  }

  /**
   * Get selector
   * @return selector
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public VLabelSelector getSelector() {
    return selector;
  }


  public void setSelector(VLabelSelector selector) {
    this.selector = selector;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VMetricIdentifier vMetricIdentifier = (VMetricIdentifier) o;
    return Objects.equals(this.name, vMetricIdentifier.name) &&
            Objects.equals(this.selector, vMetricIdentifier.selector);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, selector);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VMetricIdentifier {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    selector: ").append(toIndentedString(selector)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

