/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: release-1.16
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.coding.apiserver.models;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Webhook holds the configuration of the webhook
 */
@ApiModel(description = "Webhook holds the configuration of the webhook")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-04-29T07:27:12.312Z[Etc/UTC]")
public class VWebhook {
  public static final String SERIALIZED_NAME_CLIENT_CONFIG = "clientConfig";
  @SerializedName(SERIALIZED_NAME_CLIENT_CONFIG)
  private VWebhookClientConfig clientConfig;

  public static final String SERIALIZED_NAME_THROTTLE = "throttle";
  @SerializedName(SERIALIZED_NAME_THROTTLE)
  private VWebhookThrottleConfig throttle;


  public VWebhook clientConfig(VWebhookClientConfig clientConfig) {

    this.clientConfig = clientConfig;
    return this;
  }

   /**
   * Get clientConfig
   * @return clientConfig
  **/
  @ApiModelProperty(required = true, value = "")

  public VWebhookClientConfig getClientConfig() {
    return clientConfig;
  }


  public void setClientConfig(VWebhookClientConfig clientConfig) {
    this.clientConfig = clientConfig;
  }


  public VWebhook throttle(VWebhookThrottleConfig throttle) {

    this.throttle = throttle;
    return this;
  }

   /**
   * Get throttle
   * @return throttle
  **/

  @ApiModelProperty(value = "")

  public VWebhookThrottleConfig getThrottle() {
    return throttle;
  }


  public void setThrottle(VWebhookThrottleConfig throttle) {
    this.throttle = throttle;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VWebhook v1alpha1Webhook = (VWebhook) o;
    return Objects.equals(this.clientConfig, v1alpha1Webhook.clientConfig) &&
        Objects.equals(this.throttle, v1alpha1Webhook.throttle);
  }

  @Override
  public int hashCode() {
    return Objects.hash(clientConfig, throttle);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1Webhook {\n");
    sb.append("    clientConfig: ").append(toIndentedString(clientConfig)).append("\n");
    sb.append("    throttle: ").append(toIndentedString(throttle)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

